on:
  push:
    branches: [ making-hw-2 ]
  
  pull_request:
    branches: [ making-hw-2 ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install
        run: |
          sudo apt-get update
          sudo apt install cppcheck pip valgrind gcovr
          sudo pip install cpplint
          git clone https://github.com/google/googletest.git -b release-1.11.0
          sudo apt update && sudo apt install valgrind
          pip install gcovr
          cd googletest
          mkdir build
          cd build
          cmake .. -DBUILD_GMOCK=OFF
          make
          sudo make install
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
      - name: cppcheck
        run: |
          cppcheck --enable=all --error-exitcode=1 --language=c --inconclusive project/common/ project/parallel/ project/sequential/ project/main.c --suppress=missingInclude
      - name: cpplint
        run: |
          cpplint --extensions="c,h" --filter="-build/include_subdir,-legal/copyright" --linelength=120 project/common/* project/parallel/* project/sequential/* project/main.c
      - name: Run tests
        run: |
          cd build
          ./test_common
          ./test_sequential
          ./test_parallel
      - name: Run tests with valgrind
        run: |
          cd build
          valgrind --tool=memcheck --leak-check=full --show-reachable=yes ./test_common
          valgrind --tool=memcheck --leak-check=full --show-reachable=yes ./test_sequential
          valgrind --tool=memcheck --leak-check=full --show-reachable=yes ./test_parallel
      - name: Coverage
        run: |
          cd build
          mkdir coverage-report
          cd coverage-report
          gcovr -r ../../ -f ../../project/common/common.c -f ../../project/sequential/sequential.c -f ../../project/parallel/parallel.c -o coverage-report.xml --xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: 44f13f3e-0ded-4ca7-8ca1-6f9182297590
          files: ./build/coverage-report/coverage-report.xml