on:
  push:
    branches: [ making-hw-1 ]

jobs: 
  formatting-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install clang-tidy and wget
        run: sudo apt install clang-tidy wget --yes
      
      - name: Run clang-tidy
        run: mkdir build && cd build && cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug && wget https://raw.githubusercontent.com/llvm-mirror/clang-tools-extra/master/clang-tidy/tool/run-clang-tidy.py && python3 run-clang-tidy.py
        