on:
  push:
    branches: [ making-hw-1 ]

jobs: 
  formatting-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Install all
        run: sudo apt install cppcheck cpplint --yes
      
      - name: Run cppcheck
        run: cppcheck project --enable=all --inconclusive --error-exitcode=1 -I project/include --suppress=missingIncludeSystem
      
      -name: Run cpplint
        run: cpplint --extensions="c,h" --filter="-build/include_subdir,-legal/copyright" --linelength=120 project/include/* project/src/* 
      