on:
  push:
    branches: [ making-hw-1 ]
  
  pull_request:
    branches: [ making-hw-1 ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          sudo apt install cppcheck pip --yes
          sudo pip install cpplint

      - name: Run cppcheck
        run: cppcheck project --enable=all --inconclusive --error-exitcode=1 -I project/include --suppress=missingIncludeSystem

      - name: Run cpplint
        run: cpplint --extensions="c,h" --filter="-build/include_subdir,-legal/copyright" --linelength=120 project/include/* project/src/*

  tests:
    runs-on: ubuntu-latest
    needs: [ format-check ]
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          git clone https://github.com/google/googletest.git -b release-1.11.0
          sudo apt update && sudo apt install valgrind
          pip install gcovr
          cd googletest
          mkdir build
          cd build
          cmake .. -DBUILD_GMOCK=OFF
          make
          sudo make install

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run GTest
        run: |
          cd build
          ./test_lib

      - name: Run GTest with Valgrind
        run: |
          cd build
          valgrind --tool=memcheck --leak-check=full ./test_lib

      - name: Coverage
        run: |
          cd build
          mkdir coverage-report
          cd coverage-report
          gcovr -r ../../ --filter ../../project/src/ -o coverage-report.xml --xml
          
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: —Åoverage report
          path: build/coverage-report
            